import { DependencyList } from 'react';
export declare type BaseOptions<R, P extends any[]> = {
  refreshDeps?: DependencyList;
  manual?: boolean;
  onSuccess?: (data: R, params: P) => void;
  onError?: (e: Error, params: P) => void;
  defaultLoading?: boolean;
  loadingDelay?: number;
  defaultParams?: P;
  pollingInterval?: number;
  pollingWhenHidden?: boolean;
  fetchKey?: (...args: P) => string;
  paginated?: false;
  loadMore?: false;
  refreshOnWindowFocus?: boolean;
  focusTimespan?: number;
  cacheKey?: string | number;
  cacheTime?: number;
  staleTime?: number;
  debounceInterval?: number;
  throttleInterval?: number;
  initialData?: R;
  requestMethod?: (service: any) => Promise<any>;
  ready?: boolean;
  throwOnError?: boolean;
};
